import { Suspense } from "react";
import "./globals.css";
import { inter } from "./font"
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  RedirectToSignIn,
} from "@clerk/nextjs";
import AppHeader from "@/components/AppHeader/AppHeader";


import { headers } from 'next/headers'
import App from "next/app";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Clerk Test App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const pathname = usePathname();
  const pathname = headers().get('x-invoke-path') as string;
  console.log(`pathname: ${pathname}`);

  const isPublic = ["/"].includes(pathname);
  console.log(`isPublic: ${isPublic}`)
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          <AppHeader />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
